// resources/js/Pages/Dashboard.tsx
import { useState } from 'react';
import { Head, Link, router } from '@inertiajs/react';
import axios from 'axios';
import { Radio, Rss, Trash2 } from 'lucide-react';

import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout';
import AddSubscriptionForm from '@/AppComponents/AddSubscriptionForm';
import ErrorPanel from '@/AppComponents/ErrorPanel';
import routes from '@/routes';
import { Badge } from '@/Components/ui/badge';
import { Button } from '@/Components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/Components/ui/card';
import {
    AlertDialog,
    AlertDialogAction,
    AlertDialogCancel,
    AlertDialogContent,
    AlertDialogDescription,
    AlertDialogFooter,
    AlertDialogHeader,
    AlertDialogTitle,
    AlertDialogTrigger,
} from '@/Components/ui/alert-dialog';

type Feed = {
    id: number;
    uuid: string;
    name: string;
    description: string;
    subscription_id: number | null;
    audio_clips_count: number;
};

type User = {
    feeds: Feed[];
};

export default function Dashboard({ user }: { user: User }) {
    const [errorMessage, setErrorMessage] = useState('');
    const [isLoading, setIsLoading] = useState(false);

    const reloadUser = () => router.reload({ only: ['user'] });

    const deleteFeed = (feed: Feed) => {
        setErrorMessage('');
        setIsLoading(true);

        axios
            .delete(routes.api.deleteFeed(feed.id))
            .then(() => {
                reloadUser();
                setIsLoading(false);
            })
            .catch((error) => {
                setIsLoading(false);
                setErrorMessage(
                    error.response?.data?.message ?? error.response?.data?.error,
                );
            });
    };

    return (
        <AuthenticatedLayout
            header={
                <div className="flex items-end justify-between gap-4">
                    <h1 className="font-display text-4xl font-extrabold tracking-tight sm:text-5xl">
                        Your <span className="accent-underline">feeds</span>
                    </h1>
                    <span className="hidden shrink-0 rounded-full border-2 border-ink bg-secondary px-3 py-1 text-sm font-bold text-secondary-foreground shadow-hard-sm sm:inline-block">
                        {user.feeds.length}{' '}
                        {user.feeds.length === 1 ? 'feed' : 'feeds'}
                    </span>
                </div>
            }
        >
            <Head title="Feeds" />

            <div className="grid gap-6 lg:grid-cols-3">
                <div className="space-y-4 lg:col-span-2">
                    {errorMessage !== '' && (
                        <ErrorPanel
                            message={errorMessage}
                            operation="deleting your feed"
                        />
                    )}

                    {user.feeds.length === 0 ? (
                        <Card className="border-dashed">
                            <CardContent className="py-12 text-center">
                                <Rss className="mx-auto size-8 text-muted-foreground/50" />
                                <p className="mt-3 font-display text-lg font-bold">
                                    No feeds yet
                                </p>
                                <p className="mt-1 text-sm text-muted-foreground">
                                    Create your first feed to start collecting clips.
                                </p>
                            </CardContent>
                        </Card>
                    ) : (
                        <ul className="space-y-3">
                            {user.feeds.map((feed) => (
                                <li key={feed.id}>
                                    <Card className="gap-0 py-0 transition-all hover:-translate-x-px hover:-translate-y-px hover:shadow-hard-lg">
                                        <div className="flex flex-col gap-4 p-4 sm:flex-row sm:items-center sm:justify-between">
                                            <div className="min-w-0">
                                                <Link
                                                    href={routes.feed(feed.id)}
                                                    className="font-display text-lg font-bold transition-colors hover:text-primary"
                                                >
                                                    {feed.name}
                                                </Link>
                                                <div className="mt-1.5 flex items-center gap-2">
                                                    <Badge
                                                        variant={
                                                            feed.subscription_id == null
                                                                ? 'secondary'
                                                                : 'default'
                                                        }
                                                    >
                                                        {feed.subscription_id == null ? (
                                                            <Rss />
                                                        ) : (
                                                            <Radio />
                                                        )}
                                                        {feed.subscription_id == null
                                                            ? 'Custom'
                                                            : 'Subscription'}
                                                    </Badge>
                                                    <span className="text-xs font-semibold text-muted-foreground">
                                                        {feed.audio_clips_count}{' '}
                                                        {feed.audio_clips_count === 1
                                                            ? 'clip'
                                                            : 'clips'}
                                                    </span>
                                                </div>
                                            </div>

                                            <div className="flex flex-none items-center gap-2">
                                                <Button
                                                    asChild
                                                    variant="outline"
                                                    size="sm"
                                                >
                                                    <a
                                                        href={routes.rss(feed.uuid)}
                                                        target="_blank"
                                                        rel="noreferrer"
                                                    >
                                                        <Rss />
                                                        RSS
                                                    </a>
                                                </Button>

                                                <AlertDialog>
                                                    <AlertDialogTrigger asChild>
                                                        <Button
                                                            variant="ghost"
                                                            size="icon"
                                                            className="text-muted-foreground hover:text-destructive"
                                                            disabled={isLoading}
                                                            aria-label={`Delete ${feed.name}`}
                                                        >
                                                            <Trash2 />
                                                        </Button>
                                                    </AlertDialogTrigger>
                                                    <AlertDialogContent>
                                                        <AlertDialogHeader>
                                                            <AlertDialogTitle>
                                                                Delete {feed.name}?
                                                            </AlertDialogTitle>
                                                            <AlertDialogDescription>
                                                                This permanently removes
                                                                the feed and its RSS
                                                                link. This can't be
                                                                undone.
                                                            </AlertDialogDescription>
                                                        </AlertDialogHeader>
                                                        <AlertDialogFooter>
                                                            <AlertDialogCancel>
                                                                Cancel
                                                            </AlertDialogCancel>
                                                            <AlertDialogAction
                                                                onClick={() =>
                                                                    deleteFeed(feed)
                                                                }
                                                                className="bg-destructive text-destructive-foreground hover:brightness-110"
                                                            >
                                                                Delete feed
                                                            </AlertDialogAction>
                                                        </AlertDialogFooter>
                                                    </AlertDialogContent>
                                                </AlertDialog>
                                            </div>
                                        </div>
                                    </Card>
                                </li>
                            ))}
                        </ul>
                    )}
                </div>

                <div className="lg:col-span-1">
                    <Card className="lg:sticky lg:top-24">
                        <CardHeader>
                            <CardTitle className="flex items-center gap-2">
                                <span className="grid size-7 place-items-center rounded-lg border-2 border-ink bg-accent text-foreground">
                                    <Rss className="size-4" />
                                </span>
                                New feed
                            </CardTitle>
                        </CardHeader>
                        <CardContent>
                            <AddSubscriptionForm onCreated={reloadUser} />
                        </CardContent>
                    </Card>
                </div>
            </div>
        </AuthenticatedLayout>
    );
}

// resources/js/Pages/Dashboard.vue
<script setup lang="ts">
import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout.vue';
import {Head, Link, router} from '@inertiajs/vue3';
import routes from "@/routes";
import AddSubscriptionForm from "@/AppComponents/AddSubscriptionForm.vue";
import Panel from "@/Components/Panel.vue";
import PanelList from "@/Components/PanelList.vue";
import PanelListItem from "@/Components/PanelListItem.vue";
import axios from "axios";
import {ref} from "vue";
import ErrorPanel from "@/AppComponents/ErrorPanel.vue";

type User = {
    feeds: Array<Feed>,
}

type Feed = {
    id: number,
    uuid: string,
    name: string,
    description: string,
    subscription_id: number|null,
    audio_clips_count: number,
}

const title: string = 'Feeds';

defineProps<{user: User}>()

const errorMessage = ref<string>('');
const isLoading = ref<boolean>(false);

const reloadUser = () => router.reload({only: ['user']});

const deleteFeed = (feed: Feed) => {
    if (!confirm(`Are you sure you want to delete ${feed.name}?`)) { return; }

    errorMessage.value = '';
    isLoading.value = true;

    axios.delete(routes.api.deleteFeed(feed.id))
        .then(() => {
            reloadUser();

            isLoading.value = false;
        })
        .catch((error) => {
            isLoading.value = false;

            errorMessage.value = error.response.data.message ?? error.response.data.error;
        });
};

</script>

<template>
    <Head :title="title" />

    <AuthenticatedLayout>
<!--        <template #header>
            <h2 class="font-semibold text-xl text-gray-800 leading-tight">{{title}}</h2>
        </template>-->

        <div class="max-w-7xl mx-auto py-6 px-4 sm:px-6 lg:px-8 space-y-6">
            <ErrorPanel v-if="errorMessage != ''"
                        :message="errorMessage"
                        operation="deleting your feed" />

            <Panel>
                <AddSubscriptionForm @createNewFeed="reloadUser" />
            </Panel>

            <PanelList>
                <PanelListItem
                    v-for="feed in user.feeds"
                    :key="feed.id"
                    :class="'flex flex-col sm:flex-row items-stretch sm:items-center justify-between gap-y-2 sm:gap-x-6'"
                >
                    <!-- First Div: Metadata -->
                    <div class="min-w-0">
                        <Link :href="routes.feed(feed.id)" class="flex items-start gap-x-3">
                            <p class="text-sm font-semibold leading-6 text-gray-900">{{ feed.name }}</p>
                        </Link>
                        <div class="mt-1 flex items-center gap-x-2 text-xs/5 text-gray-500">
                            <p class="whitespace-nowrap">{{ feed.subscription_id == null ? 'Custom' : 'Subscription' }}</p>
                            <svg viewBox="0 0 2 2" class="size-0.5 fill-current">
                                <circle cx="1" cy="1" r="1" />
                            </svg>
                            <p class="whitespace-nowrap">{{ feed.audio_clips_count }} clips <!--todo: pluralize--></p>
                        </div>
                    </div>

                    <!-- Second Div: Buttons -->
                    <div class="flex flex-none items-center gap-x-4">
                        <a
                            target="_blank"
                            class="inline-flex items-center space-x-2 rounded-md bg-white px-2.5 py-1.5 text-sm font-semibold text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 hover:bg-gray-50"
                            :href="routes.rss(feed.uuid)"
                        >
                            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-5">
                                <path
                                    stroke-linecap="round"
                                    stroke-linejoin="round"
                                    d="M12.75 19.5v-.75a7.5 7.5 0 0 0-7.5-7.5H4.5m0-6.75h.75c7.87 0 14.25 6.38 14.25 14.25v.75M6 18.75a.75.75 0 1 1-1.5 0 .75.75 0 0 1 1.5 0Z"
                                />
                            </svg>
                            <span>RSS</span>
                        </a>
                        <button
                            @click="deleteFeed(feed)"
                            class="rounded-md bg-white px-2.5 py-1.5 text-sm font-semibold text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 hover:bg-gray-50"
                            :disabled="isLoading"
                        >
                            <svg
                                xmlns="http://www.w3.org/2000/svg"
                                fill="none"
                                viewBox="0 0 24 24"
                                stroke-width="1.5"
                                stroke="currentColor"
                                class="size-5"
                            >
                                <path
                                    stroke-linecap="round"
                                    stroke-linejoin="round"
                                    d="m14.74 9-.346 9m-4.788 0L9.26 9m9.968-3.21c.342.052.682.107 1.022.166m-1.022-.165L18.16 19.673a2.25 2.25 0 0 1-2.244 2.077H8.084a2.25 2.25 0 0 1-2.244-2.077L4.772 5.79m14.456 0a48.108 48.108 0 0 0-3.478-.397m-12 .562c.34-.059.68-.114 1.022-.165m0 0a48.11 48.11 0 0 1 3.478-.397m7.5 0v-.916c0-1.18-.91-2.164-2.09-2.201a51.964 51.964 0 0 0-3.32 0c-1.18.037-2.09 1.022-2.09 2.201v.916m7.5 0a48.667 48.667 0 0 0-7.5 0"
                                />
                            </svg>
                        </button>
                    </div>
                </PanelListItem>
                <PanelListItem v-show="user.feeds.length === 0">
                    No feeds to display.
                </PanelListItem>
            </PanelList>
        </div>
    </AuthenticatedLayout>
</template>
