// resources/js/Pages/Feed.tsx
import { useEffect, useState } from 'react';
import { Head, router } from '@inertiajs/react';
import axios from 'axios';
import { format, parseISO } from 'date-fns';
import { ExternalLink, Radio, Rss, Trash2 } from 'lucide-react';

import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout';
import AddClipForm from '@/AppComponents/AddClipForm';
import ErrorPanel from '@/AppComponents/ErrorPanel';
import events from '@/events';
import routes from '@/routes';
import { AudioClip, ClipProcessingState, Feed as FeedType } from '@/types';
import { Badge } from '@/Components/ui/badge';
import { Button } from '@/Components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/Components/ui/card';
import {
    AlertDialog,
    AlertDialogAction,
    AlertDialogCancel,
    AlertDialogContent,
    AlertDialogDescription,
    AlertDialogFooter,
    AlertDialogHeader,
    AlertDialogTitle,
    AlertDialogTrigger,
} from '@/Components/ui/alert-dialog';
import { cn } from '@/lib/utils';

type StateName = ClipProcessingState['name'];

const STATE_VARIANT: Record<
    StateName,
    'warning' | 'success' | 'secondary' | 'destructive'
> = {
    Processing: 'warning',
    Processed: 'success',
    Unavailable: 'secondary',
    Failed: 'destructive',
};

function StatusBadge({ state }: { state: ClipProcessingState }) {
    const variant = STATE_VARIANT[state.name] ?? 'destructive';
    const label = STATE_VARIANT[state.name] ? state.name : 'Unknown';

    return (
        <Badge variant={variant}>
            <span
                className={cn(
                    'size-1.5 rounded-full',
                    variant === 'warning' && 'bg-warning animate-signal',
                    variant === 'success' && 'bg-success',
                    variant === 'destructive' && 'bg-destructive',
                    variant === 'secondary' && 'bg-muted-foreground/60',
                )}
            />
            {label}
        </Badge>
    );
}

function formatDate(value: string): string {
    try {
        return format(parseISO(value), 'MMM do yyyy');
    } catch {
        return value;
    }
}

export default function Feed({ feed }: { feed: FeedType }) {
    const [errorMessage, setErrorMessage] = useState('');
    const [isLoading, setIsLoading] = useState(false);

    const reloadFeed = () => router.reload({ only: ['feed'] });

    useEffect(() => {
        const channel = events.finishedProcessingClip(feed.id);
        channel.listen(() => router.reload({ only: ['feed'] }));

        return () => channel.leave();
    }, [feed.id]);

    const deleteClip = (clip: AudioClip) => {
        setErrorMessage('');
        setIsLoading(true);

        axios
            .delete(routes.api.deleteClip(feed.id, clip.id))
            .then(() => {
                reloadFeed();
                setIsLoading(false);
            })
            .catch((error) => {
                setIsLoading(false);
                setErrorMessage(
                    error.response?.data?.message ?? error.response?.data?.error,
                );
            });
    };

    const clipCount = feed.audio_clips.length;

    return (
        <AuthenticatedLayout
            header={
                <div>
                    <span className="inline-flex items-center gap-1.5 rounded-full border-2 border-ink bg-secondary px-3 py-1 text-xs font-bold text-secondary-foreground shadow-hard-sm">
                        {feed.subscription != null ? (
                            <>
                                <Radio className="size-3.5" />
                                {feed.subscription.name} ·{' '}
                                {feed.subscription.platform_type.name}
                            </>
                        ) : (
                            <>
                                <Rss className="size-3.5" />
                                Custom feed
                            </>
                        )}
                    </span>
                    <h1 className="mt-3 font-display text-4xl font-extrabold tracking-tight sm:text-5xl">
                        {feed.name}
                    </h1>
                    <p className="mt-1 text-sm font-semibold text-muted-foreground">
                        {clipCount} {clipCount === 1 ? 'clip' : 'clips'}
                    </p>
                </div>
            }
        >
            <Head title={feed.name} />

            <div className="space-y-6">
                {errorMessage !== '' && (
                    <ErrorPanel
                        message={errorMessage}
                        operation="deleting your clip"
                    />
                )}

                {feed.subscription == null && (
                    <Card>
                        <CardHeader>
                            <CardTitle className="text-base">Add a clip</CardTitle>
                        </CardHeader>
                        <CardContent>
                            <AddClipForm feedId={feed.id} onAdded={reloadFeed} />
                        </CardContent>
                    </Card>
                )}

                {clipCount === 0 ? (
                    <Card className="border-dashed">
                        <CardContent className="py-12 text-center text-sm text-muted-foreground">
                            No clips to display yet.
                        </CardContent>
                    </Card>
                ) : (
                    <ul className="space-y-2">
                        {feed.audio_clips.map((clip) => (
                            <li key={clip.id}>
                                <Card className="gap-0 py-0 transition-all hover:-translate-x-px hover:-translate-y-px hover:shadow-hard-lg">
                                    <div className="flex items-start justify-between gap-4 p-4">
                                        <div className="min-w-0 flex-1">
                                            <div className="flex flex-wrap items-center gap-2">
                                                <p className="font-bold">
                                                    {clip.title}
                                                </p>
                                                <StatusBadge
                                                    state={clip.processing_state}
                                                />
                                                <Badge variant="outline">
                                                    {
                                                        clip.audio_source
                                                            .platform_type.name
                                                    }
                                                </Badge>
                                            </div>
                                            <div className="mt-1.5 flex flex-wrap items-center gap-x-2 gap-y-1 font-mono text-xs text-muted-foreground">
                                                <span>From {clip.audio_source.name}</span>
                                                <span className="opacity-40">/</span>
                                                <span>
                                                    Published{' '}
                                                    {formatDate(clip.published_at)}
                                                </span>
                                                <span className="opacity-40">/</span>
                                                <span>
                                                    Added {formatDate(clip.created_at)}
                                                </span>
                                            </div>
                                        </div>

                                        <div className="flex flex-none items-center gap-1">
                                            <Button
                                                asChild
                                                variant="ghost"
                                                size="icon"
                                                className="text-muted-foreground hover:text-foreground"
                                            >
                                                <a
                                                    href={clip.platform_url}
                                                    target="_blank"
                                                    rel="noreferrer"
                                                    aria-label="Open source"
                                                >
                                                    <ExternalLink />
                                                </a>
                                            </Button>

                                            <AlertDialog>
                                                <AlertDialogTrigger asChild>
                                                    <Button
                                                        variant="ghost"
                                                        size="icon"
                                                        className="text-muted-foreground hover:text-destructive"
                                                        disabled={isLoading}
                                                        aria-label={`Delete ${clip.title}`}
                                                    >
                                                        <Trash2 />
                                                    </Button>
                                                </AlertDialogTrigger>
                                                <AlertDialogContent>
                                                    <AlertDialogHeader>
                                                        <AlertDialogTitle>
                                                            Delete this clip?
                                                        </AlertDialogTitle>
                                                        <AlertDialogDescription>
                                                            "{clip.title}" will be
                                                            removed from this feed. This
                                                            can't be undone.
                                                        </AlertDialogDescription>
                                                    </AlertDialogHeader>
                                                    <AlertDialogFooter>
                                                        <AlertDialogCancel>
                                                            Cancel
                                                        </AlertDialogCancel>
                                                        <AlertDialogAction
                                                            onClick={() =>
                                                                deleteClip(clip)
                                                            }
                                                            className="bg-destructive text-destructive-foreground hover:brightness-110"
                                                        >
                                                            Delete clip
                                                        </AlertDialogAction>
                                                    </AlertDialogFooter>
                                                </AlertDialogContent>
                                            </AlertDialog>
                                        </div>
                                    </div>
                                </Card>
                            </li>
                        ))}
                    </ul>
                )}
            </div>
        </AuthenticatedLayout>
    );
}

// resources/js/Pages/Feed.vue
<script setup lang="ts">

import {Head, router} from "@inertiajs/vue3";
import AuthenticatedLayout from "@/Layouts/AuthenticatedLayout.vue";
import AddClipForm from "@/AppComponents/AddClipForm.vue";
import events from "@/events";
import {AudioClip, Feed} from "@/types";
import moment from "moment/moment";
import axios, {AxiosResponse} from "axios";
import routes from "@/routes";
import {ref} from "vue";
import PanelList from "@/Components/PanelList.vue";
import PanelListItem from "@/Components/PanelListItem.vue";
import ErrorPanel from "@/AppComponents/ErrorPanel.vue";

const props = defineProps<{feed: Feed}>();

const reloadFeed = () => router.reload({only: ['feed']});

const errorMessage = ref<string>('');
const isLoading = ref<boolean>(false);

const deleteClip = (clip: AudioClip) => {
    if (!confirm(`Are you sure you want to delete ${clip.title}?`)) { return; }

    errorMessage.value = '';
    isLoading.value = true;

    axios.delete(routes.api.deleteClip(props.feed.id, clip.id))
        .then(() => {
            reloadFeed();

            isLoading.value = false;
        })
        .catch((error) => {
            isLoading.value = false;

            errorMessage.value = error.response.data.message ?? error.response.data.error;
        });
}

events.finishedProcessingClip(props.feed.id).listen(reloadFeed);

console.log(props.feed);

</script>

<template>

    <Head :title="feed.name" />

    <AuthenticatedLayout>
        <template #header>
            <h3 class="font-semibold text-xl text-gray-800 leading-tight">{{feed.name}}</h3>
            <div class="mt-1 flex items-center gap-x-2 text-xs/5 text-gray-500">
                <p v-if="feed.subscription != null" class="whitespace-nowrap">
                    Subscription to {{ feed.subscription.name }} on {{ feed.subscription.platform_type.name }}
                </p>
                <p v-else class="whitespace-nowrap">
                    Custom feed
                </p>
                <svg viewBox="0 0 2 2" class="size-0.5 fill-current">
                    <circle cx="1" cy="1" r="1" />
                </svg>
                <p class="whitespace-nowrap">
                    {{ feed.audio_clips.length }} {{ feed.audio_clips.length > 1 ? 'clips' : 'clip' }}
                </p>
            </div>
        </template>

        <ErrorPanel v-if="errorMessage != ''"
                    :message="errorMessage"
                    operation="deleting your clip" />

        <div class="max-w-7xl mx-auto py-6 px-4 sm:px-6 lg:px-8 space-y-6">
            <AddClipForm v-if="feed.subscription == null" :feed-id="feed.id" @add-clip="reloadFeed"/>

            <PanelList>
                <PanelListItem v-for="clip in feed.audio_clips" :key="clip.id" :class="'flex items-center justify-between gap-x-6'">
                    <div class="min-w-0">
                        <div class="flex items-start gap-x-3">
                            <p class="text-sm font-semibold leading-6 text-gray-900">{{clip.title}}</p>
                            <p v-if="clip.processing_state.name == 'Processing'" class="rounded-md whitespace-nowrap mt-0.5 px-1.5 py-0.5 text-xs font-medium ring-1 ring-inset text-yellow-800 bg-yellow-50 ring-yellow-600/20">
                                Processing
                            </p>
                            <p v-else-if="clip.processing_state.name == 'Processed'" class="rounded-md whitespace-nowrap mt-0.5 px-1.5 py-0.5 text-xs font-medium ring-1 ring-inset text-green-700 bg-green-50 ring-green-600/20">
                                Processed
                            </p>
                            <p v-else-if="clip.processing_state.name == 'Unavailable'" class="rounded-md whitespace-nowrap mt-0.5 px-1.5 py-0.5 text-xs font-medium ring-1 ring-inset text-gray-700 bg-green-50 ring-gray-600/20">
                                Unavailable
                            </p>
                            <p v-else>
                                Unknown (Error)
                            </p>
                            <p class="rounded-md whitespace-nowrap mt-0.5 px-1.5 py-0.5 text-xs font-medium ring-1 ring-inset text-gray-600 bg-gray-50 ring-gray-500/10">
                                {{clip.audio_source.platform_type.name}}
                            </p>
                        </div>
                        <div class="mt-1 flex items-center gap-x-2 text-xs/5 text-gray-500">
                            <p class="whitespace-nowrap">
                                From {{clip.audio_source.name}}
                            </p>
                            <svg viewBox="0 0 2 2" class="size-0.5 fill-current">
                                <circle cx="1" cy="1" r="1" />
                            </svg>
                            <p class="whitespace-nowrap">
                                Published {{moment(clip.published_at).format('MMM Do YYYY')}}
                            </p>
                            <svg viewBox="0 0 2 2" class="size-0.5 fill-current">
                                <circle cx="1" cy="1" r="1" />
                            </svg>
                            <p class="whitespace-nowrap">
                                Added {{moment(clip.created_at).format('MMM Do YYYY')}}
                            </p>
                        </div>
                    </div>

                    <div class="flex flex-none items-center gap-x-4">
                        <a
                            target="_blank"
                            class="hidden rounded-md bg-white px-2.5 py-1.5 text-sm font-semibold text-gray-900 shadow-xs ring-1 ring-inset ring-gray-300 hover:bg-gray-50 sm:block"
                            :href="clip.platform_url"
                        >
                            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-5">
                                <path stroke-linecap="round" stroke-linejoin="round" d="M13.19 8.688a4.5 4.5 0 0 1 1.242 7.244l-4.5 4.5a4.5 4.5 0 0 1-6.364-6.364l1.757-1.757m13.35-.622 1.757-1.757a4.5 4.5 0 0 0-6.364-6.364l-4.5 4.5a4.5 4.5 0 0 0 1.242 7.244" />
                            </svg>
                        </a>
                        <button
                            @click="deleteClip(clip)"
                            class="hidden rounded-md bg-white px-2.5 py-1.5 text-sm font-semibold text-gray-900 shadow-xs ring-1 ring-inset ring-gray-300 hover:bg-gray-50 sm:block"
                            :disabled="isLoading"
                        >
                            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-5">
                                <path stroke-linecap="round" stroke-linejoin="round" d="m14.74 9-.346 9m-4.788 0L9.26 9m9.968-3.21c.342.052.682.107 1.022.166m-1.022-.165L18.16 19.673a2.25 2.25 0 0 1-2.244 2.077H8.084a2.25 2.25 0 0 1-2.244-2.077L4.772 5.79m14.456 0a48.108 48.108 0 0 0-3.478-.397m-12 .562c.34-.059.68-.114 1.022-.165m0 0a48.11 48.11 0 0 1 3.478-.397m7.5 0v-.916c0-1.18-.91-2.164-2.09-2.201a51.964 51.964 0 0 0-3.32 0c-1.18.037-2.09 1.022-2.09 2.201v.916m7.5 0a48.667 48.667 0 0 0-7.5 0" />
                            </svg>
                        </button>
                    </div>
                </PanelListItem>
                <PanelListItem v-show="feed.audio_clips.length === 0">
                    No clips to display.
                </PanelListItem>
            </PanelList>
        </div>
    </AuthenticatedLayout>

</template>
